### ISSUE TITLE
Pytorch-lightning errors

### ISSUE THREAD

**Issue by sarah-allec** [drcassar/viscnet#3]
What version of pytorch-lightning is this package compatible with? I'm getting various pytorch-lightning errors (I'm using the latest version). For example, when running `train.py`:

```python
Traceback (most recent call last):
  File "train.py", line 27, in <module>
    train_model(
  File "~/Projects/viscnet/viscnet/models.py", line 472, in train_model
    trainer.fit(model, train_dl, val_dl)
  File "~/opt/anaconda3/envs/viscnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "~/opt/anaconda3/envs/viscnet/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "~/opt/anaconda3/envs/viscnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "~/opt/anaconda3/envs/viscnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 883, in _run
    _verify_loop_configurations(self)
  File "~/opt/anaconda3/envs/viscnet/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 38, in _verify_loop_configurations
    __verify_train_val_loop_configuration(trainer, model)
  File "~/opt/anaconda3/envs/viscnet/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 79, in __verify_train_val_loop_configuration
    raise NotImplementedError(
NotImplementedError: Support for `training_epoch_end` has been removed in v2.0.0. `ViscNet` implements this method. You can use the `on_train_epoch_end` hook instead. To access outputs, save them in-memory as instance attributes. You can find migration examples in https://github.com/Lightning-AI/lightning/pull/16520.
```

**Comment by drcassar** [comment]
Hi @sarah-allec. From your message, I think you would need to install an erlier version of pytorch-lightning (before v2.0.0). I would try [this version](https://pypi.org/project/pytorch-lightning/1.0.4/). 

I will archive this repository because ViscNet is now part of [GlassPy](https://github.com/drcassar/glasspy) and this repository will not be maintained anymore.

**Comment by drcassar** [comment]
@sarah-allec, I've updated the requirements.txt. It should run without errors now (tested on python 3.9).
